### PR TITLE
Typofasist and grammarnazi changes

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by tomkukral** [comment]
Every change in stanovy.tex should be approved by parlament of CTU Student Union, but I can risk it ...

**Comment by hroncok** [comment]
Those are not content changes anyway. You'll need to get it reapproved after new SU rules (stanovy) anyway I guess, because the suspended membership will be gone.

**Comment by tomkukral** [comment]
Nevermind .. thank for your changes. You are the third most valuable contributor according to the number of commits!

**Comment by hroncok** [comment]
:D

**Pull request merged**
